name: CI for otpgen

on:
  push:
    branches: [main]
  pull_request:
    branches: [main]

jobs:
  test:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        python-version: [3.11, 3.12, 3.13]

    steps:
      - uses: actions/checkout@v3

      - name: Set up Python ${{ matrix.python-version }}
        uses: actions/setup-python@v4
        with:
          python-version: ${{ matrix.python-version }}

      - name: Install ZBar (system dependency)
        run: sudo apt-get update && sudo apt-get install -y libzbar0

      - name: Install test dependencies
        run: pip install -r requirements-test.txt

      - name: Run tests
        run: tox -e py

      - name: Run linter
        run: tox -e lint

      - name: Run coverage report
        run: tox -e coverage
